### PR TITLE
IAI: Upgraded cert-manager and ingress-nginx charts.

### PR DESCRIPTION
**Pull request by karok2m**
Changes:
* Upgraded `cert-manager` Helm chart to version `1.1.0`.
* Added some code documentation.
* Upgraded `ingress-nginx` Helm chart to version `3.12.0`.
* Enabled default backend for `ingress-nginx`.
* Updated documentation of `Microsoft.Azure.IIoT.Deployment`.
* Updated documentation of adding an AKS cluster.

### CODE REVIEW

**Comment by koepalex** [comment]
> namespace Microsoft.Azure.IIoT.Deployment.Authentication {

Can you check why this file is in PR, it seems to have no changes

---
Refers to: deploy/src/Microsoft.Azure.IIoT.Deployment/Authentication/IAuthenticationManager.cs:6 in aad87ad. [](commit_id = aad87ad1ed8d6ab8ed3e4578f8d8f84b5c2f034b, deletion_comment = False)

**Review by koepalex — APPROVED** [review]
:shipit:

**Comment by karok2m** [comment]
> > namespace Microsoft.Azure.IIoT.Deployment.Authentication {
> 
> Can you check why this file is in PR, it seems to have no changes
> 
> Refers to: deploy/src/Microsoft.Azure.IIoT.Deployment/Authentication/IAuthenticationManager.cs:6 in [aad87ad](https://github.com/Azure/Industrial-IoT/commit/aad87ad1ed8d6ab8ed3e4578f8d8f84b5c2f034b). [](commit_id = [aad87ad](https://github.com/Azure/Industrial-IoT/commit/aad87ad1ed8d6ab8ed3e4578f8d8f84b5c2f034b), deletion_comment = False)

It contained a trailing whitespace which has been removed.

**Review by koepalex — APPROVED** [review]
:shipit:

**Pull request merged**
