### PR TITLE
Fix session/subscription cleanup not working when session disconnected

### PR DESCRIPTION
**Pull request by dacolgit**

### CODE REVIEW

**Review by koepalex — APPROVED** [review]
:shipit:

**Review by barnstee — COMMENTED** [review]
LGTM

**Review by cristipogacean — COMMENTED** [review]
what happens when the session owns more than one subscription?

**Comment by dacolgit** [comment]
> what happens when the session owns more than one subscription?
just checked it works

**Comment by cristipogacean** [comment]
I don't think the subscription manager should trigger directly removal of the owning session, but the session manager should exclusively remove sessions.

I have just run in an null reference exception that I have never seen before and I suspect this change is the reason:
image

**Pull request merged**
