### PR TITLE
IAI: Upgraded NuGet packages.

### PR DESCRIPTION
**Pull request by karok2m**

### CODE REVIEW

**Review by koepalex — DISMISSED** [review]
General question: should we use the `*-preview` NuGet packages for production?

**Comment by barnstee** [comment]
> General question: should we use the `*-preview` NuGet packages for production?

No we should not, unless there is nothing else?

**Review by koepalex — APPROVED** [review]
:shipit:

**Comment by karok2m** [comment]
> > General question: should we use the `*-preview` NuGet packages for production?
> 
> No we should not, unless there is nothing else?

Ideally we shouldn't if there are non-preview versions. But most of `Microsoft.Azure.Management.*` NuGet packages are still in preview and there are no non-preview versions of them. In my last commit I migrated to `Microsoft.Graph` from `Microsoft.Graph.Beta`, which is only possible since recently.

**Pull request merged**
