### PR TITLE
Fixing parsing of version in deployment scripts.

### PR DESCRIPTION
**Pull request by karok2m**
The code has been tested with the following commands on Windows:

```bash
.\deploy.cmd -version "2.7.199"
.\deploy.cmd -version "2.7.199" -type all
.\deploy.cmd -type all -version "2.7.199"
.\deploy.cmd -version
```

The code has been tested with the following commands on Linux:

```bash
./deploy.sh -version "2.7.199"
./deploy.sh -version "2.7.199" -type all
./deploy.sh -type all -version "2.7.199"
./deploy.sh -version
```

### CODE REVIEW

**Comment by karok2m** [comment]
Fixes: Unable to select version on deployment script #862

**Comment by luiscantero** [comment]
Please check these scenarios as well: PR #662 ... I think you will have to go back to findstr.

**Review by luiscantero — CHANGES_REQUESTED** [review]
Please check these scenarios as well: PR #662

**Comment by mregen** [comment]
@karok2m did you also try the -alpha flag?

**Comment by karok2m** [comment]
> Please check these scenarios as well: PR #662

I've additionally tested the following cases:

For windows:
```bash
.\deploy.cmd -resourceGroupName rg-kakostan-test -version 2.7.183
.\deploy.cmd -resourceGroupName rg-kakostan-test
```
For Linux:
```bash
./deploy.sh -resourceGroupName rg-kakostan-test -version 2.7.183
./deploy.sh -resourceGroupName rg-kakostan-test
```

**Comment by karok2m** [comment]
> @karok2m did you also try the -alpha flag?

@mregen, I've checked that when the version is passed from command line as `2.8.103-alpha`, then the image tag is detected as exactly that. I have not deployed that version though. 

```bash
./deploy.sh -resourceGroupName rg-kakostan-test -version 2.8.103-alpha
```

**Review by monikavar — DISMISSED** [review]

**Review by luiscantero — APPROVED** [review]

**Review by luiscantero — APPROVED** [review]

**Review by mregen — APPROVED** [review]

**Pull request merged**
