### PR TITLE
Update tut-timeseriesinsights.md

### PR DESCRIPTION
**Pull request by ChenCheng368**
The TSI explorer url format provided in .env file is not accurate anymore. It will lead to ERR_CONNECTION_TIMED_OUT.
A better practice is to access TSI explorer by url from TSI environment resource.

### CODE REVIEW

**Comment by ChenCheng368** [comment]
I am not allowed to upload the picture to /doc/media. The link in the commit without picture uploaded will fail. 

I attach the picture for the link here first.
tut-tsi-retrieve-url
e.

**Comment by karok2m** [comment]
@ChenCheng368, since this is a PR from your fork, wouldn't you be able to add the image to the branch on your fork ?

**Comment by ChenCheng368** [comment]
> @karok2m , The image is supposed to be uploaded to /Industrial-IoT/docs/media with a name "tut-tsi-retrieve-url.png".
I have tried to Upload Files in the directory from my fork, 


and then here comes up "Upload are disabled".


Is it a proper way to upload the file?

**Comment by karok2m** [comment]
> > @karok2m , The image is supposed to be uploaded to /Industrial-IoT/docs/media with a name "tut-tsi-retrieve-url.png".
> > I have tried to Upload Files in the directory from my fork,
> > 
> 
> and then here comes up "Upload are disabled". 
> 
> Is it a proper way to upload the file?

@ChenCheng368, here you are trying to upload it directly to our repository, for which you do not have permissions. Instead you should add it to `docs/media` directory locally on your machine and then commit it to your `patch-2` branch on your fork. It will then show up in the PR as well.

**Comment by ChenCheng368** [comment]
> 

Thanks, uploaded already.

**Review by karok2m — APPROVED** [review]

**Comment by karok2m** [comment]
Run of the tests for this branch can be found [here](https://msazure.visualstudio.com/One/_build/results?buildId=50636792&view=results).

**Pull request merged**
