### PR TITLE
Updated 3rd party notice file.

### PR DESCRIPTION
**Pull request by karok2m**

### CODE REVIEW

**Comment by cristipogacean** [comment]
is the new NOTICE file generated?

**Review by mregen — COMMENTED** [review]
OPCF NOTICE needs to be at the beginning

**Comment by karok2m** [comment]
> is the new NOTICE file generated?

Yes, this is generated by the SDL task. I took this one from a build for latest `main`.

**Comment by karok2m** [comment]
> OPCF NOTICE needs to be at the beginning

@mregen, I've moved OPC Foundation license to the top of the file as in the template. I have also moved other MIT license notices for `OPCFoundation.NetStandard.Opc.Ua.*` packages just under it. Are those actually required when we have the big entry for `OPCFoundation.NetStandard.Opc.Ua.Core` before them ?

**Comment by cristipogacean** [comment]
> Copyright (c) <year> <copyright holders>

Is the usage of placeholders intended here? I think we should have the real values like 2022 OPC Foundation, Inc. Same goes for the next packages.

---
Refers to: NOTICE:1005 in 687b074. [](commit_id = 687b074e0fd1633846f2e4e2f2bca117fb39d606, deletion_comment = False)

**Comment by karok2m** [comment]
> > Copyright (c)
> 
> Is the usage of placeholders intended here? I think we should have the real values like 2022 OPC Foundation, Inc. Same goes for the next packages.
> 
> Refers to: NOTICE:1005 in [687b074](https://github.com/Azure/Industrial-IoT/commit/687b074e0fd1633846f2e4e2f2bca117fb39d606). [](commit_id = [687b074](https://github.com/Azure/Industrial-IoT/commit/687b074e0fd1633846f2e4e2f2bca117fb39d606), deletion_comment = False)

You are referring to `Copyright (c) <year> <copyright holders>` placeholders, right ? Those were present for `OPCFoundation` packages (and others) previously as well. I am not sure why are some having this entry and others have it filled with valid data. Looks like it can be a notice generation issue or something along those lines.

**Review by cristipogacean — APPROVED** [review]

**Review by monikavar — APPROVED** [review]

**Pull request merged**
