### PR TITLE
temporarily disable default pn.json schema validation 

### PR DESCRIPTION
**Pull request by cristipogacean**
Temporarily disable default pn.json schema validation because of backwards compatibility issues:
* the validation schema is too restrictive with non-standard OPC UA namespace uris like the ones used by Kepserver. Even though the namespace uri definition is well defined in the OPC UA Spec, we find many opc ua servers in the field that use non-compliant uri strings. E.g.  "nsu=KEPServerEX;s=Sim.xxx". 
* the schema validation does not support NodeID in the IIoT Platform (twin defined) ExpandedNodeId format: "Namespaceuri#IdentifierUnion" e.g. `"Id": "http://test.org/UA/Data/#i=10847",`
* ExpandedNodeId is missing from OpcNode definition

Validation can enabled by specifying the right file using --pfs(publishfileschema) argument

### CODE REVIEW

**Comment by karok2m** [comment]
Should we open a GitHub Issue for this to add support of those formats in the validation scheme and keep track of the work ?

Tagging @suneetnangia and @WilliamBerryiii as they originally implemented this feature in #1305.

**Review by karok2m — APPROVED** [review]

**Comment by suneetnangia** [comment]
> Should we open a GitHub Issue for this to add support of those formats in the validation scheme and keep track of the work ?
> 
> Tagging @suneetnangia and @WilliamBerryiii as they originally implemented this feature in #1305.



> Should we open a GitHub Issue for this to add support of those formats in the validation scheme and keep track of the work ?
> 
> Tagging @suneetnangia and @WilliamBerryiii as they originally implemented this feature in #1305.

@karok2m Agreed, we should open an issue and track it, not using schema validation should be exception than a norm, although from backward compatibility perspective we could just make validation disabled by default. Currently, if we want to bypass schema validation, we can do that explicitly by providing no value to --pfs param e.g. --pfs="" which also throws the warning to surface the fact that validation is skipped. If customer has something specific to themselves, they can add in the schema file to avoid validation error and warning and continue to take benefit of the schema validation, if this is more common than specific customer, we should/could add it in the schema. KepServer one above looks like falling in the latter case.

**Review by dacolgit — APPROVED** [review]

**Review by monikavar — APPROVED** [review]

**Comment by WilliamBerryiii** [comment]
@cristipogacean - can you give some specifics about how you see stuff failing?

- the validation schema is too restrictive with non-standard OPC UA namespace uris like the ones used by Kepserver. Even though the namespace uri definition is well defined in the OPC UA Spec, we find many opc ua servers in the field that use non-compliant uri strings. E.g. "nsu=KEPServerEX;s=Sim.xxx".

If you have a recommendation for how far we should pull back from validating that the NSU is a valid URL/URN - I'm happy to update the schema. As an aside, the value validation for the ID property can be disabled by removing the "pattern property" from the ID field of the schema. 

https://github.com/Azure/Industrial-IoT/blob/c7184f7cbd8b507933722cbd6e995f871ed19b86/modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/Schemas/publishednodesschema.json#L47

- the schema validation does not support NodeID in the IIoT Platform (twin defined) ExpandedNodeId format: "Namespaceuri#IdentifierUnion" e.g. "Id": "http://test.org/UA/Data/#i=10847",

The schema does support "nsu", "ns" and "nodeid" formats (see above pattern match). If is not working, can you provide an example pn.json section that we can test against? 

- ExpandedNodeId is missing from OpcNode definition

ExpandedNodeId is supported in the second sub-schema definition (see this line: https://github.com/Azure/Industrial-IoT/blob/c7184f7cbd8b507933722cbd6e995f871ed19b86/modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/Schemas/publishednodesschema.json#L114). Can you provide an example pn.json section that we can test against? 

Thanks!

**Comment by cristipogacean** [comment]
@WilliamBerryiii, @suneetnangia 

First-of-all we really appreciate your contributions! The schema validation is a really valuable addition to the OPC Publisher and we're looking forward to fill in the existing gaps and integrate it as a default enabled product feature.

The pn.json that I had issues with is the following: 
```
[
	{
	"EndpointUrl": "opc.tcp://crpogace01:49320",
	"UseSecurity": false,
	"OpcNodes": [
			{
				
				"DisplayName": "Kep_1_DisplayName",
				"DataSetFieldId": "Kep_1_DataSetFieldId",
				"Id": "nsu=KEPServerEX;s=Sim.CH1.SIM_CH1_TAG1\\234754a-c63-b9601",
				"OpcSamplingInterval": 1000,
				"OpcPublishingInterval": 1000
			},
			{
				"DisplayName": "Kep_2_DisplayName",
				"DataSetFieldId": "Kep_2_DataSetFieldId",
				"Id": "ns=2;s=Sim.CH1.SIM_CH1_TAG10\\2347798-c63-19401",
				"ExpandedNodeId":"nsu=KEPServerEX;s=Sim.CH1.SIM_CH1_TAG10\\2347798-c63-19401",
				"OpcSamplingInterval": 1000,
				"OpcPublishingInterval": 1000
			}
		]
	},
	{
	"EndpointUrl": "opc.tcp://crpogace01:51210/UA/DemoServer",
	"UseSecurity": false,
	"OpcNodes": [
			{
				"DisplayName": "Softing_1_DisplayName",
				"DataSetFieldId": "Softing_1_DataSetFieldId",
				"Id": "http://test.org/UA/Data/#i=10847",
				"OpcSamplingInterval": 1000,
				"OpcPublishingInterval": 1000
			},
			{
				"DisplayName": "Softing_2_DisplayName",
				"DataSetFieldId": "Softing_2_DataSetFieldId",
				"Id": "nsu=http://test.org/UA/Data/;i=10848",
				"OpcSamplingInterval": 1000,
				"OpcPublishingInterval": 1000
			},
			{
				"DisplayName": "Softing_3_DisplayName",
				"DataSetFieldId": "Softing_3_DataSetFieldId",
				"Id": "ns=3;i=10849",
				"ExpandedNodeId":"http://test.org/UA/Data/#i=10849",
				"OpcSamplingInterval": 1000,
				"OpcPublishingInterval": 1000
			}
		]
	}
]
```

On my original points:

* **OPC UA namespace uris** - I believe we should just validate that namespace uri is a string. I have seen too many uncompliant forms uris in market established OPC UA servers that I believe the best strategy to avoid support cases here is to expect the unexpected. I've seen, besides well formatted uris, uris starting with uri.xxx, urn.xxx, random (application specific) strings like KEPServerEX, I have even seen empty strings for namespace uris in some server.
* **Namespaceuri#IdentifierUnion** - this is the format that we use in the IIoT platform cloud based microservices as well as in the opc twin module, therefore we need to support it in the pn.json file as well. 
* **ExpandedNodeId** - just based on a quick review I had the impression that `Id` and `ExpandedNodeId` are mutual exclusive in the. Maybe I was wrong about this. Please find above the example I tested with. 

Thank you very much!

**Comment by WilliamBerryiii** [comment]
@cristipogacean - thanks for the sample and I'll take a look at this today.  

I don't believe the project's unit tests or configuration files we've run across included any examples where `Id` and `ExpandedNodeId` were used in the same OpcNodes configuration set; so if the mixed use of `Id` and `ExpandedNodeId` is a real example (e.g. a config file that spanned multiple generations of OPC Publisher), then I'd propose we should: 

- update the schema to not be mutually exclusive arrays for `Id` and `ExpandedNodeId` - relatively trivial change. I intentionally kept them discrete to reflect the [generational config file comments](https://github.com/Azure/Industrial-IoT/blob/c7184f7cbd8b507933722cbd6e995f871ed19b86/docs/modules/publishednodes.json#L50) in the sample pn.json file
- add supporting unit tests to the [schema generator/validator](https://github.com/WilliamBerryiii/opcpublisherschemavalidator) to document the mixed use of `Id` and `ExpandedNodeId` as an operational requirement   
- add supporting unit tests to OPC Publisher to document the mixed use of `Id` and `ExpandedNodeId` as an operational requirement  
- update the example pn.json example file to note that it's permissible to mix them (not sure if this would encourage folks ... so maybe skip it?)
- back off the value pattern matches to just a string type match (we can do this, regardless, by simply removing the pattern element from the schema)

I can get you a PR pretty quickly on this, if you'd like help.

Few other points to note:

- We should absolutely prioritize not breaking any existing implementations of users; and it would be good to document these cases via unit tests so that future changes to (de)serialization routines don't accidentally break folks.  
- The [schema generator/validator](https://github.com/WilliamBerryiii/opcpublisherschemavalidator) can be used in local dev loops to update/upgrade existing config flies. The generator/validator uses AJV as the backing schema utility and can be run either as a local toolchain or in the context of a CI/CD pipeline to "upgrade" or enforce consistency of config files.
- I'd love some thoughts on if we can improve the project's documentation around config file format upgrading and how the schema can be leveraged to improve the quality of existing user's config files. I.E. would it help to have a tool built that could take old or mixed format pn.json config files, attempt an upgrade and show recommended changes for compatibility - like migration to NSU style ids?

Should we move the conversation to an issue?

Thanks again for the samples and happy to support dev cycles on this.

**Pull request merged**
