### PR TITLE
Updating IIoT Dashboard and fixing publisher metrics endpoint

### PR DESCRIPTION
**Pull request by monikavar**
Since iotedge team released the official version of azureiotedge-metrics-collector module, the tables and their schema inside LogAnalytics workspace were updated. This PR updates the IIoT Platform dashboard queries.

Additionally, there was a bug introduced while updating the official metrics-collector module i.e., incorrect endpoint was provided for scraping publisher metrics. This PR also fixes it.

**Before:**

error_in_dashboard
**After:**

image

### CODE REVIEW

**Comment by karok2m** [comment]
@monikavar, can you please attach pictures of how the broken and now fixed dashboards look like ? It is impossible to understand the scope of the change from the change of the JSON file itself.

**Comment by monikavar** [comment]
> @monikavar, can you please attach pictures of how the broken and now fixed dashboards look like ? It is impossible to understand the scope of the change from the change of the JSON file itself.

Updated PR description with before and after screenshots.

**Comment by koepalex** [comment]
> > @monikavar
> >             
> >             Monika Varshney
> >             FTE, can you please attach pictures of how the broken and now fixed dashboards look like ? It is impossible to understand the scope of the change from the change of the JSON file itself.
> 
> Updated PR description with before and after screenshots.

Are you sure? the images look identically ...

**Comment by monikavar** [comment]
> > > @monikavar
> > > ```
> > >         Monika Varshney
> > >         FTE, can you please attach pictures of how the broken and now fixed dashboards look like ? It is impossible to understand the scope of the change from the change of the JSON file itself.
> > > ```
> > 
> > 
> > Updated PR description with before and after screenshots.
> 
> Are you sure? the images look identically ...

Thanks for catching. Fixed now.

**Comment by koepalex** [comment]
> > > > @monikavar
> > > >             
> > > >             Monika Varshney
> > > >             FTE
> > > > ```
> > > >         Monika Varshney
> > > >         FTE, can you please attach pictures of how the broken and now fixed dashboards look like ? It is impossible to understand the scope of the change from the change of the JSON file itself.
> > > > ```
> > > 
> > > 
> > > Updated PR description with before and after screenshots.
> > 
> > 
> > Are you sure? the images look identically ...
> 
> Thanks for catching. Fixed now.

I don't want to be nitpicky but could you use an after screenshot were really something is monitored and the OPC Publisher is active pushing data into IoT Hub?

**Comment by monikavar** [comment]
> > > > > @monikavar
> > > > > ```
> > > > >         Monika Varshney
> > > > >         FTE
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > ```
> > > > >         Monika Varshney
> > > > >         FTE, can you please attach pictures of how the broken and now fixed dashboards look like ? It is impossible to understand the scope of the change from the change of the JSON file itself.
> > > > > ```
> > > > 
> > > > 
> > > > Updated PR description with before and after screenshots.
> > > 
> > > 
> > > Are you sure? the images look identically ...
> > 
> > 
> > Thanks for catching. Fixed now.
> 
> I don't want to be nitpicky but could you use an after screenshot were really something is monitored and the OPC Publisher is active pushing data into IoT Hub?

@koepalex - There was a bug - also fixed the bug in this PR. Latest dashboard image is attached.

**Review by koepalex — DISMISSED** [review]
:shipit:

**Comment by koepalex** [comment]
test needs to be adopted: Microsoft.Azure.IIoT.OpcUa.Registry.Tests.Deploy.IoTHubMetricsCollectorDeploymentTests.MetricsCollectorDeploymentRoutesTestAsync

**Review by karok2m — APPROVED** [review]

**Pull request merged**
