### PR TITLE
Send events one by one through the pipeline

### PR DESCRIPTION
**Pull request by peterbryntesson**
fix: When receiving multiple events in the event callback, the code now sends them one-by-one through the processing pipeline.

### CODE REVIEW

**Comment by simonjaeger** [comment]
@peterbryntesson The formatting in SubscriptionService.cs is strange. It makes the diff hard to read. Can you look at it? The indentation has been changed.

**Review by simonjaeger — APPROVED** [review]
LGTM

**Review by simonjaeger — CHANGES_REQUESTED** [review]
Tests failing. Let's investigate.

**Review by simonjaeger — APPROVED** [review]

**Comment by simonjaeger** [comment]
All good. Was an old run. All tests pass in the new run.

**Review by koepalex — APPROVED** [review]
:shipit:

**Pull request merged**
